language: node_js
node_js:
  - 14
arch: amd64
env:
  global:
    - CAS_VERSION=6.2.0

addons:
  hosts:
    - cas.example.org


services:
  - docker

before_install:
  - docker pull osixia/openldap
  - docker pull apereo/cas:v$CAS_VERSION
  - docker run -d -p 8080:8080  --name openldap -e LDAP_DOMAIN="activimetrics.com" \
           -e LDAP_ORGANIZATION="Activimetrics LLC"  -e LDAP_ADMIN_PASSWORD="grobblefruit"    --volume ${PWD}/test/ldap_restore/ldif_dump.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif  osixia/openldap  --copy-service
  - docker run -d  -p 8443:8443 --name="cas"  apereo/cas:v$CAS_VERSION

before_script:
  - while [ $? -ne 0 ]; do sleep 5 && curl -v -k http://localhost:8080; done

  # - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  # - chmod +x ./cc-test-reporter
  # - ./cc-test-reporter before-build

# notifications:
#   email:
#     on_success: change
#     on_failure: change

# after_script:
#   - ./node_modules/.bin/tap --coverage-report=lcov &&  ./cc-test-reporter after-build  -t lcov --exit-code $TRAVIS_TEST_RESULT
